/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenix
 */
public class IdentifyCustomer extends javax.swing.JFrame {
        private String staffId;
        private boolean isAdmin;

	public IdentifyCustomer(String staffId, boolean isAdmin) {
            this.staffId = staffId;
            this.isAdmin = isAdmin;
            initComponents();
            setLocationRelativeTo(null);
            loadCustomerInformation();
	}


    private void loadCustomerInformation() {
        try (java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.FileReader("customers.txt"))) {
            String line;
			DefaultTableModel model = (DefaultTableModel) CustomerInfoTable.getModel();
			model.setRowCount(0); // Clear existing rows
            while ((line = reader.readLine()) != null) {
                String[] data = line.split(",");
				User.setUsername(data[0]);
				User.loadEncryptedPassword(data[1]);
                        
				Customer.setUsername(data[0]);
				Customer.setName(data[2]);
				Customer.setGender(data[3]);
				
				model.addRow(new Object[]{
					Customer.getUsername(),
					Customer.getGender(),
					Customer.getName()
				});
			}
		} catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error reading user data!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        CustomerInfoTable = new javax.swing.JTable();
        backToStaffMenu = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CustomerInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Gender", "Customer Name"
            }
        ));
        jScrollPane2.setViewportView(CustomerInfoTable);

        backToStaffMenu.setText("Back to Staff Menu");
        backToStaffMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToStaffMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToStaffMenu)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backToStaffMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToStaffMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToStaffMenuActionPerformed
        // TODO add your handling code here:
		new Staff_Menu(staffId, isAdmin).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_backToStaffMenuActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(IdentifyCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(IdentifyCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(IdentifyCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(IdentifyCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CustomerInfoTable;
    private javax.swing.JButton backToStaffMenu;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
